resources:
# Automation scripts repo
  - name: azure_vnet_tf_repo
    type: gitRepo
    integration: "drship_github"
    versionTemplate:
      sourceName: "sample-organisation/prov_azure_vnet_terraform" # TODO: change to org name to devops-recipies
      branch: master

# Azure credentials
  - name: azure_vnet_tf_creds
    type: integration
    integration: "drship_azure"

# Terraform State
  - name: azure_vnet_tf_state
    type: state

# Output of Virtual Network provisioning
  - name: azure_vnet_tf_info
    type: params
    versionTemplate:
      params:
        SEED: "initial_version"

jobs:
# Provision Azure VM with Terraform
  - name: prov_azure_vnet_tf
    type: runSh
    steps:
      # - IN: aws_vpc_tf_info # TODO see the link between vpc
      - IN: azure_vnet_tf_repo
        switch: off
      - IN: azure_vnet_tf_state
        switch: off
      - IN: azure_vnet_tf_creds
        switch: off
      - TASK:
          name: prov_vnet
          runtime:
            options:
              env: # TODO: edit envs
                - resource_group_name: "demo_rg_tf"
                - resource_group_location: "eastus"
          script:
            - pushd $(shipctl get_resource_state "azure_vnet_tf_repo")
            - shipctl copy_file_from_resource_state azure_vnet_tf_state terraform.tfstate .
            - shipctl replace terraform.tfvars
            - terraform plan -var-file=terraform.tfvars
            # - terraform apply -var-file=terraform.tfvars
      - OUT: azure_vnet_tf_info
        overwrite: true
      - OUT: azure_vnet_tf_state
    on_success:
      script:
        - echo "TODO"
        # - shipctl put_resource_state_multi aws_ec2_tf_info "versionName=$(terraform output ec2_ins_0_ip)" "ec2_ins_0_ip=$(terraform output ec2_ins_0_ip)"
    always:
      script:
        - shipctl copy_file_to_resource_state terraform.tfstate azure_vnet_tf_state
        - popd
    flags:
      - azure_vnet
      - azure
      - terraform
